### ISSUE TITLE
Hack does not progress to the next firewall 

### ISSUE THREAD

**Issue by En013** [Special-Operations-Brigade/SOB-Issue-Tracker#335] opened 2024-03-07 23:24 UTC
Issue reported by Saber

**Link to .rpt file**
https://discord.com/channels/1009176668998488164/1206563752326074471/1206763387355267102

**Comment by ThatArcanist** [comment] 2024-03-08 11:42
This has yet to happen again, believed to be a funny arma moment. Keeping open a little bit to see if its reported again

**Comment by ThatArcanist** [comment] 2024-03-26 11:03
Ample time has passed, closing this as cannot reproduce

**Closed as not planned by ThatArcanist** 2024-03-26 11:03 UTC
Labels: Bug, Cannot Reproduce
