### ISSUE TITLE
The Commando Fireing Device Doesent work with the following

### ISSUE THREAD

**Issue by Hex9909** [Special-Operations-Brigade/SOB-Issue-Tracker#79] opened 2022-07-28 18:28 UTC
**Describe the bug**
The CFD does not work with the APERS minedispenser cant use it on the Dispenser
the IR laser dont seem to work with the claymore or Slam. 
the tripwire also doesnt work SOMETIMES

**To Reproduce**
1. Go to 'Arma3'
2. Click on 'Claymore'
3. Scroll down to 'fireing device'

**Expected behavior**
for me to trip the IR laser and for the Device to explode.

**Screenshots**

**Mods List:**
 - Arca Company Modset: Y/N

**Additional context**

**Comment by m0kka** [comment] 2022-07-31 19:44
Missing compats have been added, could not reproduce the IR/PROX failing to work with either Claymores or SLAMs

**Comment by m0kka** [comment] 2022-11-06 13:08
haven't had any complaints about this in a while, closing as resolved

**Closed by m0kka** 2022-11-06 13:08 UTC
Labels: bug, feedback needed
