### ISSUE TITLE
CovOps disguise kits do not have the merc option in arsenel 

### ISSUE THREAD

**Issue by En013** [Special-Operations-Brigade/SOB-Issue-Tracker#333] opened 2024-03-07 23:18 UTC
Bug found by Saber

**Comment by ThatArcanist** [comment] 2024-03-08 17:38
Duplicate of https://github.com/Special-Operations-Brigade/SOB-Issue-Tracker/issues/288

**Closed as not planned by ThatArcanist** 2024-03-08 17:38 UTC
Labels: Bug, Duplicate, Confirmed, Low priority
